// flow-typed signature: 03df6c14b02ef439cb54cb436d5bd963
// flow-typed version: <<STUB>>/bin-build_v^3.0.0/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bin-build'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bin-build' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bin-build/index' {
  declare module.exports: $Exports<'bin-build'>;
}
declare module 'bin-build/index.js' {
  declare module.exports: $Exports<'bin-build'>;
}
