// flow-typed signature: a189ccc0fbdbd8aa131c0557fccb6563
// flow-typed version: <<STUB>>/bin-wrapper_v^4.1.0/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bin-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bin-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bin-wrapper/index' {
  declare module.exports: $Exports<'bin-wrapper'>;
}
declare module 'bin-wrapper/index.js' {
  declare module.exports: $Exports<'bin-wrapper'>;
}
