// flow-typed signature: be2329b4e6f044210a298643c9d47fc2
// flow-typed version: <<STUB>>/eslint-scope_v^5.1.1/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-scope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-scope' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-scope/lib/definition' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib/pattern-visitor' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib/reference' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib/referencer' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib/scope-manager' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib/scope' {
  declare module.exports: any;
}

declare module 'eslint-scope/lib/variable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-scope/lib/definition.js' {
  declare module.exports: $Exports<'eslint-scope/lib/definition'>;
}
declare module 'eslint-scope/lib/index' {
  declare module.exports: $Exports<'eslint-scope/lib'>;
}
declare module 'eslint-scope/lib/index.js' {
  declare module.exports: $Exports<'eslint-scope/lib'>;
}
declare module 'eslint-scope/lib/pattern-visitor.js' {
  declare module.exports: $Exports<'eslint-scope/lib/pattern-visitor'>;
}
declare module 'eslint-scope/lib/reference.js' {
  declare module.exports: $Exports<'eslint-scope/lib/reference'>;
}
declare module 'eslint-scope/lib/referencer.js' {
  declare module.exports: $Exports<'eslint-scope/lib/referencer'>;
}
declare module 'eslint-scope/lib/scope-manager.js' {
  declare module.exports: $Exports<'eslint-scope/lib/scope-manager'>;
}
declare module 'eslint-scope/lib/scope.js' {
  declare module.exports: $Exports<'eslint-scope/lib/scope'>;
}
declare module 'eslint-scope/lib/variable.js' {
  declare module.exports: $Exports<'eslint-scope/lib/variable'>;
}
