// flow-typed signature: b80dda8332df39e0db8377d55630b070
// flow-typed version: <<STUB>>/espree_v^7.3.0/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'espree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'espree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'espree/espree' {
  declare module.exports: any;
}

declare module 'espree/lib/ast-node-types' {
  declare module.exports: any;
}

declare module 'espree/lib/espree' {
  declare module.exports: any;
}

declare module 'espree/lib/features' {
  declare module.exports: any;
}

declare module 'espree/lib/options' {
  declare module.exports: any;
}

declare module 'espree/lib/token-translator' {
  declare module.exports: any;
}

declare module 'espree/lib/visitor-keys' {
  declare module.exports: any;
}

// Filename aliases
declare module 'espree/espree.js' {
  declare module.exports: $Exports<'espree/espree'>;
}
declare module 'espree/lib/ast-node-types.js' {
  declare module.exports: $Exports<'espree/lib/ast-node-types'>;
}
declare module 'espree/lib/espree.js' {
  declare module.exports: $Exports<'espree/lib/espree'>;
}
declare module 'espree/lib/features.js' {
  declare module.exports: $Exports<'espree/lib/features'>;
}
declare module 'espree/lib/options.js' {
  declare module.exports: $Exports<'espree/lib/options'>;
}
declare module 'espree/lib/token-translator.js' {
  declare module.exports: $Exports<'espree/lib/token-translator'>;
}
declare module 'espree/lib/visitor-keys.js' {
  declare module.exports: $Exports<'espree/lib/visitor-keys'>;
}
