// flow-typed signature: fb4994febb8e0b8755408393042db212
// flow-typed version: <<STUB>>/fabric_v^4.2.0/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fabric'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fabric' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fabric/build' {
  declare module.exports: any;
}

declare module 'fabric/dist/fabric' {
  declare module.exports: any;
}

declare module 'fabric/dist/fabric.min' {
  declare module.exports: any;
}

declare module 'fabric/HEADER' {
  declare module.exports: any;
}

declare module 'fabric/lib/aligning_guidelines' {
  declare module.exports: any;
}

declare module 'fabric/lib/centering_guidelines' {
  declare module.exports: any;
}

declare module 'fabric/lib/event' {
  declare module.exports: any;
}

declare module 'fabric/publish' {
  declare module.exports: any;
}

declare module 'fabric/src/brushes/base_brush.class' {
  declare module.exports: any;
}

declare module 'fabric/src/brushes/circle_brush.class' {
  declare module.exports: any;
}

declare module 'fabric/src/brushes/pattern_brush.class' {
  declare module.exports: any;
}

declare module 'fabric/src/brushes/pencil_brush.class' {
  declare module.exports: any;
}

declare module 'fabric/src/brushes/spray_brush.class' {
  declare module.exports: any;
}

declare module 'fabric/src/canvas.class' {
  declare module.exports: any;
}

declare module 'fabric/src/color.class' {
  declare module.exports: any;
}

declare module 'fabric/src/control.class' {
  declare module.exports: any;
}

declare module 'fabric/src/controls.actions' {
  declare module.exports: any;
}

declare module 'fabric/src/controls.render' {
  declare module.exports: any;
}

declare module 'fabric/src/elements_parser' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/2d_backend.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/base_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/blendcolor_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/blendimage_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/blur_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/brightness_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/colormatrix_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/composed_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/contrast_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/convolute_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/filter_boilerplate' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/filter_generator' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/gamma_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/grayscale_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/hue_rotation.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/invert_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/noise_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/pixelate_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/removecolor_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/resize_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/saturate_filter.class' {
  declare module.exports: any;
}

declare module 'fabric/src/filters/webgl_backend.class' {
  declare module.exports: any;
}

declare module 'fabric/src/globalFabric' {
  declare module.exports: any;
}

declare module 'fabric/src/gradient.class' {
  declare module.exports: any;
}

declare module 'fabric/src/intersection.class' {
  declare module.exports: any;
}

declare module 'fabric/src/log' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/animation.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/canvas_dataurl_exporter.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/canvas_events.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/canvas_gestures.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/canvas_grouping.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/canvas_serialization.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/collection.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/default_controls' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/itext_behavior.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/itext_click_behavior.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/itext_key_behavior.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/itext.svg_export' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/object_geometry.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/object_interactivity.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/object_origin.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/object_stacking.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/object_straightening.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/object.svg_export' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/observable.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/shared_methods.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/stateful.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/mixins/text_style.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/parser' {
  declare module.exports: any;
}

declare module 'fabric/src/pattern.class' {
  declare module.exports: any;
}

declare module 'fabric/src/point.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shadow.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/active_selection.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/circle.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/ellipse.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/group.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/image.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/itext.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/line.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/object.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/path.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/polygon.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/polyline.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/rect.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/text.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/textbox.class' {
  declare module.exports: any;
}

declare module 'fabric/src/shapes/triangle.class' {
  declare module.exports: any;
}

declare module 'fabric/src/static_canvas.class' {
  declare module.exports: any;
}

declare module 'fabric/src/util/anim_ease' {
  declare module.exports: any;
}

declare module 'fabric/src/util/animate_color' {
  declare module.exports: any;
}

declare module 'fabric/src/util/animate' {
  declare module.exports: any;
}

declare module 'fabric/src/util/dom_event' {
  declare module.exports: any;
}

declare module 'fabric/src/util/dom_misc' {
  declare module.exports: any;
}

declare module 'fabric/src/util/dom_request' {
  declare module.exports: any;
}

declare module 'fabric/src/util/dom_style' {
  declare module.exports: any;
}

declare module 'fabric/src/util/lang_array' {
  declare module.exports: any;
}

declare module 'fabric/src/util/lang_class' {
  declare module.exports: any;
}

declare module 'fabric/src/util/lang_object' {
  declare module.exports: any;
}

declare module 'fabric/src/util/lang_string' {
  declare module.exports: any;
}

declare module 'fabric/src/util/misc' {
  declare module.exports: any;
}

declare module 'fabric/src/util/named_accessors.mixin' {
  declare module.exports: any;
}

declare module 'fabric/src/util/path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fabric/build.js' {
  declare module.exports: $Exports<'fabric/build'>;
}
declare module 'fabric/dist/fabric.js' {
  declare module.exports: $Exports<'fabric/dist/fabric'>;
}
declare module 'fabric/dist/fabric.min.js' {
  declare module.exports: $Exports<'fabric/dist/fabric.min'>;
}
declare module 'fabric/HEADER.js' {
  declare module.exports: $Exports<'fabric/HEADER'>;
}
declare module 'fabric/lib/aligning_guidelines.js' {
  declare module.exports: $Exports<'fabric/lib/aligning_guidelines'>;
}
declare module 'fabric/lib/centering_guidelines.js' {
  declare module.exports: $Exports<'fabric/lib/centering_guidelines'>;
}
declare module 'fabric/lib/event.js' {
  declare module.exports: $Exports<'fabric/lib/event'>;
}
declare module 'fabric/publish.js' {
  declare module.exports: $Exports<'fabric/publish'>;
}
declare module 'fabric/src/brushes/base_brush.class.js' {
  declare module.exports: $Exports<'fabric/src/brushes/base_brush.class'>;
}
declare module 'fabric/src/brushes/circle_brush.class.js' {
  declare module.exports: $Exports<'fabric/src/brushes/circle_brush.class'>;
}
declare module 'fabric/src/brushes/pattern_brush.class.js' {
  declare module.exports: $Exports<'fabric/src/brushes/pattern_brush.class'>;
}
declare module 'fabric/src/brushes/pencil_brush.class.js' {
  declare module.exports: $Exports<'fabric/src/brushes/pencil_brush.class'>;
}
declare module 'fabric/src/brushes/spray_brush.class.js' {
  declare module.exports: $Exports<'fabric/src/brushes/spray_brush.class'>;
}
declare module 'fabric/src/canvas.class.js' {
  declare module.exports: $Exports<'fabric/src/canvas.class'>;
}
declare module 'fabric/src/color.class.js' {
  declare module.exports: $Exports<'fabric/src/color.class'>;
}
declare module 'fabric/src/control.class.js' {
  declare module.exports: $Exports<'fabric/src/control.class'>;
}
declare module 'fabric/src/controls.actions.js' {
  declare module.exports: $Exports<'fabric/src/controls.actions'>;
}
declare module 'fabric/src/controls.render.js' {
  declare module.exports: $Exports<'fabric/src/controls.render'>;
}
declare module 'fabric/src/elements_parser.js' {
  declare module.exports: $Exports<'fabric/src/elements_parser'>;
}
declare module 'fabric/src/filters/2d_backend.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/2d_backend.class'>;
}
declare module 'fabric/src/filters/base_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/base_filter.class'>;
}
declare module 'fabric/src/filters/blendcolor_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/blendcolor_filter.class'>;
}
declare module 'fabric/src/filters/blendimage_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/blendimage_filter.class'>;
}
declare module 'fabric/src/filters/blur_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/blur_filter.class'>;
}
declare module 'fabric/src/filters/brightness_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/brightness_filter.class'>;
}
declare module 'fabric/src/filters/colormatrix_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/colormatrix_filter.class'>;
}
declare module 'fabric/src/filters/composed_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/composed_filter.class'>;
}
declare module 'fabric/src/filters/contrast_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/contrast_filter.class'>;
}
declare module 'fabric/src/filters/convolute_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/convolute_filter.class'>;
}
declare module 'fabric/src/filters/filter_boilerplate.js' {
  declare module.exports: $Exports<'fabric/src/filters/filter_boilerplate'>;
}
declare module 'fabric/src/filters/filter_generator.js' {
  declare module.exports: $Exports<'fabric/src/filters/filter_generator'>;
}
declare module 'fabric/src/filters/gamma_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/gamma_filter.class'>;
}
declare module 'fabric/src/filters/grayscale_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/grayscale_filter.class'>;
}
declare module 'fabric/src/filters/hue_rotation.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/hue_rotation.class'>;
}
declare module 'fabric/src/filters/invert_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/invert_filter.class'>;
}
declare module 'fabric/src/filters/noise_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/noise_filter.class'>;
}
declare module 'fabric/src/filters/pixelate_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/pixelate_filter.class'>;
}
declare module 'fabric/src/filters/removecolor_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/removecolor_filter.class'>;
}
declare module 'fabric/src/filters/resize_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/resize_filter.class'>;
}
declare module 'fabric/src/filters/saturate_filter.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/saturate_filter.class'>;
}
declare module 'fabric/src/filters/webgl_backend.class.js' {
  declare module.exports: $Exports<'fabric/src/filters/webgl_backend.class'>;
}
declare module 'fabric/src/globalFabric.js' {
  declare module.exports: $Exports<'fabric/src/globalFabric'>;
}
declare module 'fabric/src/gradient.class.js' {
  declare module.exports: $Exports<'fabric/src/gradient.class'>;
}
declare module 'fabric/src/intersection.class.js' {
  declare module.exports: $Exports<'fabric/src/intersection.class'>;
}
declare module 'fabric/src/log.js' {
  declare module.exports: $Exports<'fabric/src/log'>;
}
declare module 'fabric/src/mixins/animation.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/animation.mixin'>;
}
declare module 'fabric/src/mixins/canvas_dataurl_exporter.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/canvas_dataurl_exporter.mixin'>;
}
declare module 'fabric/src/mixins/canvas_events.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/canvas_events.mixin'>;
}
declare module 'fabric/src/mixins/canvas_gestures.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/canvas_gestures.mixin'>;
}
declare module 'fabric/src/mixins/canvas_grouping.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/canvas_grouping.mixin'>;
}
declare module 'fabric/src/mixins/canvas_serialization.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/canvas_serialization.mixin'>;
}
declare module 'fabric/src/mixins/collection.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/collection.mixin'>;
}
declare module 'fabric/src/mixins/default_controls.js' {
  declare module.exports: $Exports<'fabric/src/mixins/default_controls'>;
}
declare module 'fabric/src/mixins/itext_behavior.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/itext_behavior.mixin'>;
}
declare module 'fabric/src/mixins/itext_click_behavior.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/itext_click_behavior.mixin'>;
}
declare module 'fabric/src/mixins/itext_key_behavior.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/itext_key_behavior.mixin'>;
}
declare module 'fabric/src/mixins/itext.svg_export.js' {
  declare module.exports: $Exports<'fabric/src/mixins/itext.svg_export'>;
}
declare module 'fabric/src/mixins/object_geometry.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/object_geometry.mixin'>;
}
declare module 'fabric/src/mixins/object_interactivity.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/object_interactivity.mixin'>;
}
declare module 'fabric/src/mixins/object_origin.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/object_origin.mixin'>;
}
declare module 'fabric/src/mixins/object_stacking.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/object_stacking.mixin'>;
}
declare module 'fabric/src/mixins/object_straightening.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/object_straightening.mixin'>;
}
declare module 'fabric/src/mixins/object.svg_export.js' {
  declare module.exports: $Exports<'fabric/src/mixins/object.svg_export'>;
}
declare module 'fabric/src/mixins/observable.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/observable.mixin'>;
}
declare module 'fabric/src/mixins/shared_methods.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/shared_methods.mixin'>;
}
declare module 'fabric/src/mixins/stateful.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/stateful.mixin'>;
}
declare module 'fabric/src/mixins/text_style.mixin.js' {
  declare module.exports: $Exports<'fabric/src/mixins/text_style.mixin'>;
}
declare module 'fabric/src/parser.js' {
  declare module.exports: $Exports<'fabric/src/parser'>;
}
declare module 'fabric/src/pattern.class.js' {
  declare module.exports: $Exports<'fabric/src/pattern.class'>;
}
declare module 'fabric/src/point.class.js' {
  declare module.exports: $Exports<'fabric/src/point.class'>;
}
declare module 'fabric/src/shadow.class.js' {
  declare module.exports: $Exports<'fabric/src/shadow.class'>;
}
declare module 'fabric/src/shapes/active_selection.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/active_selection.class'>;
}
declare module 'fabric/src/shapes/circle.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/circle.class'>;
}
declare module 'fabric/src/shapes/ellipse.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/ellipse.class'>;
}
declare module 'fabric/src/shapes/group.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/group.class'>;
}
declare module 'fabric/src/shapes/image.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/image.class'>;
}
declare module 'fabric/src/shapes/itext.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/itext.class'>;
}
declare module 'fabric/src/shapes/line.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/line.class'>;
}
declare module 'fabric/src/shapes/object.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/object.class'>;
}
declare module 'fabric/src/shapes/path.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/path.class'>;
}
declare module 'fabric/src/shapes/polygon.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/polygon.class'>;
}
declare module 'fabric/src/shapes/polyline.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/polyline.class'>;
}
declare module 'fabric/src/shapes/rect.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/rect.class'>;
}
declare module 'fabric/src/shapes/text.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/text.class'>;
}
declare module 'fabric/src/shapes/textbox.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/textbox.class'>;
}
declare module 'fabric/src/shapes/triangle.class.js' {
  declare module.exports: $Exports<'fabric/src/shapes/triangle.class'>;
}
declare module 'fabric/src/static_canvas.class.js' {
  declare module.exports: $Exports<'fabric/src/static_canvas.class'>;
}
declare module 'fabric/src/util/anim_ease.js' {
  declare module.exports: $Exports<'fabric/src/util/anim_ease'>;
}
declare module 'fabric/src/util/animate_color.js' {
  declare module.exports: $Exports<'fabric/src/util/animate_color'>;
}
declare module 'fabric/src/util/animate.js' {
  declare module.exports: $Exports<'fabric/src/util/animate'>;
}
declare module 'fabric/src/util/dom_event.js' {
  declare module.exports: $Exports<'fabric/src/util/dom_event'>;
}
declare module 'fabric/src/util/dom_misc.js' {
  declare module.exports: $Exports<'fabric/src/util/dom_misc'>;
}
declare module 'fabric/src/util/dom_request.js' {
  declare module.exports: $Exports<'fabric/src/util/dom_request'>;
}
declare module 'fabric/src/util/dom_style.js' {
  declare module.exports: $Exports<'fabric/src/util/dom_style'>;
}
declare module 'fabric/src/util/lang_array.js' {
  declare module.exports: $Exports<'fabric/src/util/lang_array'>;
}
declare module 'fabric/src/util/lang_class.js' {
  declare module.exports: $Exports<'fabric/src/util/lang_class'>;
}
declare module 'fabric/src/util/lang_object.js' {
  declare module.exports: $Exports<'fabric/src/util/lang_object'>;
}
declare module 'fabric/src/util/lang_string.js' {
  declare module.exports: $Exports<'fabric/src/util/lang_string'>;
}
declare module 'fabric/src/util/misc.js' {
  declare module.exports: $Exports<'fabric/src/util/misc'>;
}
declare module 'fabric/src/util/named_accessors.mixin.js' {
  declare module.exports: $Exports<'fabric/src/util/named_accessors.mixin'>;
}
declare module 'fabric/src/util/path.js' {
  declare module.exports: $Exports<'fabric/src/util/path'>;
}
