// flow-typed signature: 23986b41b25c817fd0cd7af2b1057002
// flow-typed version: <<STUB>>/is-my-json-valid_v^2.17.2/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-my-json-valid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-my-json-valid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-my-json-valid/formats' {
  declare module.exports: any;
}

declare module 'is-my-json-valid/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-my-json-valid/formats.js' {
  declare module.exports: $Exports<'is-my-json-valid/formats'>;
}
declare module 'is-my-json-valid/index' {
  declare module.exports: $Exports<'is-my-json-valid'>;
}
declare module 'is-my-json-valid/index.js' {
  declare module.exports: $Exports<'is-my-json-valid'>;
}
declare module 'is-my-json-valid/require.js' {
  declare module.exports: $Exports<'is-my-json-valid/require'>;
}
