// flow-typed signature: de4ca1f356022cfa401d88ff1ed0b6e2
// flow-typed version: <<STUB>>/optionator_v^0.9.1/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optionator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'optionator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optionator/lib/help' {
  declare module.exports: any;
}

declare module 'optionator/lib' {
  declare module.exports: any;
}

declare module 'optionator/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optionator/lib/help.js' {
  declare module.exports: $Exports<'optionator/lib/help'>;
}
declare module 'optionator/lib/index' {
  declare module.exports: $Exports<'optionator/lib'>;
}
declare module 'optionator/lib/index.js' {
  declare module.exports: $Exports<'optionator/lib'>;
}
declare module 'optionator/lib/util.js' {
  declare module.exports: $Exports<'optionator/lib/util'>;
}
