// flow-typed signature: 713f75cccc1c6d4291a788f32e6f0110
// flow-typed version: <<STUB>>/source-map-loader_v^1.1.2/flow_v0.141.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'source-map-loader/dist' {
  declare module.exports: any;
}

declare module 'source-map-loader/dist/labels-to-names' {
  declare module.exports: any;
}

declare module 'source-map-loader/dist/parse-data-url' {
  declare module.exports: any;
}

declare module 'source-map-loader/dist/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-loader/dist/cjs.js' {
  declare module.exports: $Exports<'source-map-loader/dist/cjs'>;
}
declare module 'source-map-loader/dist/index' {
  declare module.exports: $Exports<'source-map-loader/dist'>;
}
declare module 'source-map-loader/dist/index.js' {
  declare module.exports: $Exports<'source-map-loader/dist'>;
}
declare module 'source-map-loader/dist/labels-to-names.js' {
  declare module.exports: $Exports<'source-map-loader/dist/labels-to-names'>;
}
declare module 'source-map-loader/dist/parse-data-url.js' {
  declare module.exports: $Exports<'source-map-loader/dist/parse-data-url'>;
}
declare module 'source-map-loader/dist/utils.js' {
  declare module.exports: $Exports<'source-map-loader/dist/utils'>;
}
